language: android
jdk: oraclejdk7
env:
  matrix:
    - ANDROID_TARGET=30  ANDROID_ABI=armeabi-v7a

before_install:
  - echo yes | android update sdk --all --filter build-tools-22.0.1 --no-ui --force

before_script:
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - adb wait-for-device
  - adb shell input keyevent 82 &

script:
  - chmod +x gradlew
  - ./gradlew assemble connectedCheck
